const root=document.documentElement;
const nav=document.getElementById('nav');
const progress=document.querySelector('.progress span');
const modal=document.getElementById('caseModal');
const previewImage=document.getElementById('previewImage');
const previewNo=document.getElementById('previewNo');
const previewTitle=document.getElementById('previewTitle');
const previewMeta=document.getElementById('previewMeta');

window.addEventListener('scroll',()=>{nav.classList.toggle('scrolled',window.scrollY>30);const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?Math.min(100,window.scrollY/h*100):0)+'%';},{passive:true});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

const prefersReduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const filterData={
 all:{img:'assets/tac.jpg',no:'01',title:'Transport Access Control',meta:'CONA · Product problem-solving'},
 problem:{img:'assets/tac.jpg',no:'01',title:'Transport Access Control',meta:'CONA · Product problem-solving'},
 system:{img:'assets/connectone.jpg',no:'02',title:'ConnectOne by rrd',meta:'Design systems · 40+ brands'},
 enterprise:{img:'assets/pnc.jpg',no:'05',title:'PNC Brand Center',meta:'Enterprise workflows · Marketing portal'},
 data:{img:'assets/tip.jpg',no:'04',title:'Trade Intelligence Platform',meta:'Strategy& · Data & dashboards'},
 experience:{img:'assets/holiday.jpg',no:'03',title:'Holiday Magic',meta:'Coca-Cola × Publix · Experience design'},
 ai:{img:'assets/holiday.jpg',no:'03',title:'Holiday Magic',meta:'AI-assisted design · Holiday Magic + TIP'}
};

document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{
 document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');
 const key=btn.dataset.filter;const d=filterData[key];previewImage.src=d.img;previewImage.alt=d.title+' preview';previewNo.textContent=d.no;previewTitle.textContent=d.title;previewMeta.textContent=d.meta;
 document.querySelectorAll('.project').forEach(p=>{const show=key==='all'||p.dataset.tags.split(' ').includes(key);p.style.display=show?'block':'none'});
}));

document.querySelectorAll('.project').forEach(p=>p.addEventListener('mouseenter',()=>{const d=filterData[p.dataset.tags.split(' ')[0]]||filterData.all;previewImage.src=p.querySelector('img').src;previewImage.alt=p.querySelector('img').alt;previewNo.textContent=p.querySelector('.project-no').textContent;previewTitle.textContent=p.querySelector('.eyebrow').textContent.split(' · ')[0];previewMeta.textContent=p.querySelector('.eyebrow').textContent;}));

const cases={
 tac:{no:'01',label:'Transport Access Control · CONA',title:'Is a QR code generator really the ask?',image:'assets/tac.jpg',facts:[['Client','Coca-Cola Southwest Beverages'],['Role','UI/UX Designer · end to end'],['Team','20'],['Timeline','90 days'],['Platforms','Mobile app + web portal'],['Outcome','35% faster check-in · 22% better vehicle flow']],sections:[['The ask','A QR code generator for truck check-in and check-out.'],['The reality','Nine stakeholder roles, hidden scenarios such as re-entry, continuous loads, cross-dock and delays, with SAP and E2open in the mix.'],['The decision','Delays did not stop at check-in. I proposed a full portal rather than a QR-only fix, so the system could address the operational flow around the gate.'],['Testing found','Weak CTA hierarchy and missing edge cases, including re-entry and no-network states. Both were fixed before handoff.']]},
 connectone:{no:'02',label:'ConnectOne by rrd · Design system',title:'What has to hold up when 40+ brands touch it?',image:'assets/connectone.jpg',facts:[['Scale','80+ printing clients'],['Role','Product designer · design system'],['Team','15 developers'],['Timeline','1.5 years'],['Components','25–30'],['Outcome','40+ brands in active use']],sections:[['The problem','A white-label platform needed consistency while still allowing each client brand to feel like its own.'],['The system','The design system used overrideable tokens for primary colors, logos and typography rather than one-off screen decisions.'],['The result','The product could support brand variation without losing a coherent core experience.']]},
 holiday:{no:'03',label:'Holiday Magic · Coca-Cola × Publix',title:'What made last year’s experience worth remembering?',image:'assets/holiday.jpg',facts:[['Role','Lead designer · solo on ’26'],['Team','3 designers in ’25'],['Timeline','2 months'],['Platform','Interactive microsite on Wix'],['Devices','Web · tablet · mobile'],['Outcome','Client returned for ’26']],sections:[["’25 → ’26",'A banner-style holiday promo became a cinematic, story-led microsite. The client returned for a second year, so the next question was what should carry over — and what should change.'],['Design direction','The experience used story, exploration and interaction rather than relying on a conventional promotional banner.'],['AI in the work','ChatGPT supported ideation and cultural research; Claude shaped prompts; Firefly supported image generation; Magnific supported animation.']]},
 tip:{no:'04',label:'Trade Intelligence Platform · Strategy&',title:'Can a dashboard ship without a single developer?',image:'assets/tip.jpg',facts:[['Team','2 people'],['Timeline','20 days'],['Users','Trade Strategy + analysis roles'],['Source','Figma Make proof of concept'],['Focus','IA · UX · brand alignment'],['Outcome','Recommendations accepted']],sections:[['The problem','The source proof of concept followed internal modules rather than user mental models. Filters reset, and AI support sat outside the workflow.'],['The decision','I restructured the tool around how users think, so context and filters persist as someone moves from a country to a product to an opportunity.'],['AI in the work','The source was already generated in Figma Make. My role was auditing it against the brand system, fixing UX inconsistencies and bringing it to production quality.']]},
 pnc:{no:'05',label:'PNC Brand Center · Enterprise workflow',title:'How do branches make one platform their own?',image:'assets/pnc.jpg',facts:[['Role','Led end to end · mentored one designer'],['Team','2 designers'],['Timeline','3 months design'],['Users','Marketing staff · branch managers · admins'],['Iterations','3 major iterations'],['Outcome','Live · used by multiple branches and sales managers']],sections:[['The problem','Branches used inconsistent branding, employees struggled to collaborate, and admins were overloaded with access and usage management.'],['The iterations','Simpler template customization, a one-page checkout combining delivery and review, and a clearer admin dashboard with charts.'],['The result','A more usable workflow for distributed marketing teams, with clearer ownership and faster decisions.']]}
};

function openCase(key){const c=cases[key];if(!c)return;document.getElementById('modalNo').textContent=c.no;document.getElementById('modalLabel').textContent=c.label;document.getElementById('modalTitle').textContent=c.title;const img=document.getElementById('modalImage');img.src=c.image;img.alt=c.label;const body=document.getElementById('modalBody');body.innerHTML='<div class="modal-facts">'+c.facts.map(x=>'<div><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('')+'</div><div class="modal-copy">'+c.sections.map(x=>'<section><h3>'+x[0]+'</h3><p>'+x[1]+'</p></section>').join('')+'</div>';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');document.querySelector('.modal-close').focus();}

document.querySelectorAll('[data-open]').forEach(btn=>btn.addEventListener('click',()=>openCase(btn.dataset.open)));
document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}));
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open')){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}});

const ai={ideate:['01','IDEATION & CONCEPTING','Start wider. Decide faster.','ChatGPT and Gemini help me explore directions and understand the territory before I commit to a visual route.'],research:['02','RESEARCH & SYNTHESIS','Make the messy legible.','Claude and Perplexity help structure research, compare signals and turn scattered information into something I can design against.'],prototype:['03','PROTOTYPING & SPEED','Get to something testable sooner.','Figma AI, Figma Make and Miro AI accelerate flows, IA exploration and early prototypes — while design judgment stays human-led.'],produce:['04','PRODUCTION SUPPORT','Spend time where craft matters.','Firefly, Adobe Podcast and Magnific reduce production friction so more attention can go into interaction, quality and storytelling.']};
document.querySelectorAll('.ai-step').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.ai-step').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const d=ai[btn.dataset.ai];document.getElementById('aiIndex').textContent=d[0];document.getElementById('aiLabel').textContent=d[1];document.getElementById('aiTitle').textContent=d[2];document.getElementById('aiBody').textContent=d[3];}));

if(!prefersReduced&&matchMedia('(hover:hover) and (pointer:fine)').matches){const dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring');let mx=0,my=0,rx=0,ry=0;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px'});function tick(){rx+=(mx-rx)*.16;ry+=(my-ry)*.16;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(tick)}tick();document.querySelectorAll('[data-magnetic]').forEach(el=>el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.18,y=(e.clientY-r.top-r.height/2)*.18;el.style.transform=`translate(${x}px,${y}px)`}));document.querySelectorAll('[data-magnetic]').forEach(el=>el.addEventListener('mouseleave',()=>el.style.transform=''));}

const counters=document.querySelectorAll('[data-count]');const countObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const el=e.target,end=Number(el.dataset.count);if(prefersReduced){el.textContent=end}else{let n=0;const step=Math.max(1,Math.ceil(end/24));const timer=setInterval(()=>{n=Math.min(end,n+step);el.textContent=n;if(n===end)clearInterval(timer)},35)}countObs.unobserve(el)}}),{threshold:.7});counters.forEach(c=>countObs.observe(c));
